services:
  kafka:
    # Changed from bitnami/kafka to bitnamilegacy/kafka
    # Note: bitnamilegacy images do not receive security updates.
    image: 'bitnamilegacy/kafka:3.8' 
    networks:
      - kafka-cluster-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - '9092:9092'
    volumes:
      - ./kafka-data:/bitnami/kafka

networks:
  kafka-cluster-network:
    driver: bridge